<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml" lang="en">
      <head>
        <title>XML Sitemap — NetVentures</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #1e293b;
            background-color: #f8fafc;
            margin: 0;
            padding: 0;
            font-size: 14px;
            line-height: 1.6;
          }
          #content {
            max-width: 1024px;
            margin: 40px auto;
            background: #ffffff;
            padding: 36px 40px;
            border-radius: 10px;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.04);
            border: 1px solid #e2e8f0;
          }
          h1 {
            color: #0f172a;
            font-size: 26px;
            font-weight: 700;
            margin: 0 0 12px 0;
            letter-spacing: -0.02em;
          }
          p.expl {
            color: #475569;
            margin: 8px 0;
            font-size: 14px;
          }
          p.expl a {
            color: #2563eb;
            text-decoration: none;
            font-weight: 500;
          }
          p.expl a:hover {
            text-decoration: underline;
          }
          table {
            border: none;
            border-collapse: collapse;
            width: 100%;
            margin-top: 24px;
          }
          th {
            text-align: left;
            padding: 12px 16px;
            font-size: 12px;
            font-weight: 600;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: #475569;
            background-color: #f1f5f9;
            border-bottom: 2px solid #cbd5e1;
          }
          td {
            padding: 12px 16px;
            border-bottom: 1px solid #e2e8f0;
            font-size: 14px;
            color: #334155;
            word-break: break-all;
          }
          tr:nth-child(even) td {
            background-color: #f8fafc;
          }
          tr:hover td {
            background-color: #eff6ff;
          }
          td a {
            color: #1d4ed8;
            text-decoration: none;
            font-weight: 500;
          }
          td a:hover {
            color: #1e40af;
            text-decoration: underline;
          }
          .date-col {
            white-space: nowrap;
            width: 180px;
            color: #64748b;
          }
        </style>
      </head>
      <body>
        <div id="content">
          <h1>XML Sitemap — NetVentures</h1>
          <p class="expl">
            Generated by <a href="https://www.netventures.online">NetVentures</a>, this is an XML Sitemap meant for consumption by search engines such as Google and Bing.
          </p>
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <p class="expl">
              This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.
            </p>
            <table id="sitemap" cellpadding="3">
              <thead>
                <tr>
                  <th width="75%">URL</th>
                  <th width="25%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <xsl:variable name="sitemapURL">
                    <xsl:value-of select="sitemap:loc"/>
                  </xsl:variable>
                  <tr>
                    <td>
                      <a href="{$sitemapURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td class="date-col">
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &lt; 1">
            <p class="expl">
              <a href="/sitemap_index.xml">&#8592; Sitemap Index</a>
            </p>
            <p class="expl">
              This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.
            </p>
            <table id="sitemap" cellpadding="3">
              <thead>
                <tr>
                  <th width="75%">URL</th>
                  <th width="25%">Last Modified</th>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <xsl:variable name="itemURL">
                    <xsl:value-of select="sitemap:loc"/>
                  </xsl:variable>
                  <tr>
                    <td>
                      <a href="{$itemURL}"><xsl:value-of select="sitemap:loc"/></a>
                    </td>
                    <td class="date-col">
                      <xsl:value-of select="sitemap:lastmod"/>
                    </td>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>
